/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef random_CONSTANTS_H
#define random_CONSTANTS_H

#include "random_types.h"

namespace Random {

class randomConstants {
 public:
  randomConstants();

};

extern const randomConstants g_random_constants;

} // namespace

#endif
