/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RandomCache_H
#define RandomCache_H

#include <thrift/TDispatchProcessor.h>
#include "random_types.h"

namespace Random {

class RandomCacheIf {
 public:
  virtual ~RandomCacheIf() {}
  virtual void getURL(std::string& _return, const std::string& url) = 0;
};

class RandomCacheIfFactory {
 public:
  typedef RandomCacheIf Handler;

  virtual ~RandomCacheIfFactory() {}

  virtual RandomCacheIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RandomCacheIf* /* handler */) = 0;
};

class RandomCacheIfSingletonFactory : virtual public RandomCacheIfFactory {
 public:
  RandomCacheIfSingletonFactory(const boost::shared_ptr<RandomCacheIf>& iface) : iface_(iface) {}
  virtual ~RandomCacheIfSingletonFactory() {}

  virtual RandomCacheIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RandomCacheIf* /* handler */) {}

 protected:
  boost::shared_ptr<RandomCacheIf> iface_;
};

class RandomCacheNull : virtual public RandomCacheIf {
 public:
  virtual ~RandomCacheNull() {}
  void getURL(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _RandomCache_getURL_args__isset {
  _RandomCache_getURL_args__isset() : url(false) {}
  bool url;
} _RandomCache_getURL_args__isset;

class RandomCache_getURL_args {
 public:

  RandomCache_getURL_args() : url() {
  }

  virtual ~RandomCache_getURL_args() throw() {}

  std::string url;

  _RandomCache_getURL_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const RandomCache_getURL_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const RandomCache_getURL_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RandomCache_getURL_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RandomCache_getURL_pargs {
 public:


  virtual ~RandomCache_getURL_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RandomCache_getURL_result__isset {
  _RandomCache_getURL_result__isset() : success(false) {}
  bool success;
} _RandomCache_getURL_result__isset;

class RandomCache_getURL_result {
 public:

  RandomCache_getURL_result() : success() {
  }

  virtual ~RandomCache_getURL_result() throw() {}

  std::string success;

  _RandomCache_getURL_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const RandomCache_getURL_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RandomCache_getURL_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RandomCache_getURL_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RandomCache_getURL_presult__isset {
  _RandomCache_getURL_presult__isset() : success(false) {}
  bool success;
} _RandomCache_getURL_presult__isset;

class RandomCache_getURL_presult {
 public:


  virtual ~RandomCache_getURL_presult() throw() {}

  std::string* success;

  _RandomCache_getURL_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RandomCacheClient : virtual public RandomCacheIf {
 public:
  RandomCacheClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  RandomCacheClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getURL(std::string& _return, const std::string& url);
  void send_getURL(const std::string& url);
  void recv_getURL(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RandomCacheProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<RandomCacheIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RandomCacheProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getURL(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RandomCacheProcessor(boost::shared_ptr<RandomCacheIf> iface) :
    iface_(iface) {
    processMap_["getURL"] = &RandomCacheProcessor::process_getURL;
  }

  virtual ~RandomCacheProcessor() {}
};

class RandomCacheProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RandomCacheProcessorFactory(const ::boost::shared_ptr< RandomCacheIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< RandomCacheIfFactory > handlerFactory_;
};

class RandomCacheMultiface : virtual public RandomCacheIf {
 public:
  RandomCacheMultiface(std::vector<boost::shared_ptr<RandomCacheIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RandomCacheMultiface() {}
 protected:
  std::vector<boost::shared_ptr<RandomCacheIf> > ifaces_;
  RandomCacheMultiface() {}
  void add(boost::shared_ptr<RandomCacheIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getURL(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getURL(_return, url);
    }
    ifaces_[i]->getURL(_return, url);
    return;
  }

};

} // namespace

#endif
