/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "lru_constants.h"

namespace Lru {

const lruConstants g_lru_constants;

lruConstants::lruConstants() {
}

} // namespace

