/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lru_CONSTANTS_H
#define lru_CONSTANTS_H

#include "lru_types.h"

namespace Lru {

class lruConstants {
 public:
  lruConstants();

};

extern const lruConstants g_lru_constants;

} // namespace

#endif
