/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fifo_CONSTANTS_H
#define fifo_CONSTANTS_H

#include "fifo_types.h"

namespace Fifo {

class fifoConstants {
 public:
  fifoConstants();

};

extern const fifoConstants g_fifo_constants;

} // namespace

#endif
