/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fifo_constants.h"

namespace Fifo {

const fifoConstants g_fifo_constants;

fifoConstants::fifoConstants() {
}

} // namespace

