/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FifoCache_H
#define FifoCache_H

#include <thrift/TDispatchProcessor.h>
#include "fifo_types.h"

namespace Fifo {

class FifoCacheIf {
 public:
  virtual ~FifoCacheIf() {}
  virtual void getURL(std::string& _return, const std::string& url) = 0;
};

class FifoCacheIfFactory {
 public:
  typedef FifoCacheIf Handler;

  virtual ~FifoCacheIfFactory() {}

  virtual FifoCacheIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(FifoCacheIf* /* handler */) = 0;
};

class FifoCacheIfSingletonFactory : virtual public FifoCacheIfFactory {
 public:
  FifoCacheIfSingletonFactory(const boost::shared_ptr<FifoCacheIf>& iface) : iface_(iface) {}
  virtual ~FifoCacheIfSingletonFactory() {}

  virtual FifoCacheIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(FifoCacheIf* /* handler */) {}

 protected:
  boost::shared_ptr<FifoCacheIf> iface_;
};

class FifoCacheNull : virtual public FifoCacheIf {
 public:
  virtual ~FifoCacheNull() {}
  void getURL(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _FifoCache_getURL_args__isset {
  _FifoCache_getURL_args__isset() : url(false) {}
  bool url;
} _FifoCache_getURL_args__isset;

class FifoCache_getURL_args {
 public:

  FifoCache_getURL_args() : url() {
  }

  virtual ~FifoCache_getURL_args() throw() {}

  std::string url;

  _FifoCache_getURL_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const FifoCache_getURL_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const FifoCache_getURL_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FifoCache_getURL_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class FifoCache_getURL_pargs {
 public:


  virtual ~FifoCache_getURL_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _FifoCache_getURL_result__isset {
  _FifoCache_getURL_result__isset() : success(false) {}
  bool success;
} _FifoCache_getURL_result__isset;

class FifoCache_getURL_result {
 public:

  FifoCache_getURL_result() : success() {
  }

  virtual ~FifoCache_getURL_result() throw() {}

  std::string success;

  _FifoCache_getURL_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const FifoCache_getURL_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const FifoCache_getURL_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FifoCache_getURL_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _FifoCache_getURL_presult__isset {
  _FifoCache_getURL_presult__isset() : success(false) {}
  bool success;
} _FifoCache_getURL_presult__isset;

class FifoCache_getURL_presult {
 public:


  virtual ~FifoCache_getURL_presult() throw() {}

  std::string* success;

  _FifoCache_getURL_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class FifoCacheClient : virtual public FifoCacheIf {
 public:
  FifoCacheClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  FifoCacheClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getURL(std::string& _return, const std::string& url);
  void send_getURL(const std::string& url);
  void recv_getURL(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class FifoCacheProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<FifoCacheIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (FifoCacheProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getURL(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  FifoCacheProcessor(boost::shared_ptr<FifoCacheIf> iface) :
    iface_(iface) {
    processMap_["getURL"] = &FifoCacheProcessor::process_getURL;
  }

  virtual ~FifoCacheProcessor() {}
};

class FifoCacheProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  FifoCacheProcessorFactory(const ::boost::shared_ptr< FifoCacheIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< FifoCacheIfFactory > handlerFactory_;
};

class FifoCacheMultiface : virtual public FifoCacheIf {
 public:
  FifoCacheMultiface(std::vector<boost::shared_ptr<FifoCacheIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~FifoCacheMultiface() {}
 protected:
  std::vector<boost::shared_ptr<FifoCacheIf> > ifaces_;
  FifoCacheMultiface() {}
  void add(boost::shared_ptr<FifoCacheIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getURL(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getURL(_return, url);
    }
    ifaces_[i]->getURL(_return, url);
    return;
  }

};

} // namespace

#endif
